// Generated by gencpp from file tutorial/MulTwoInts.msg
// DO NOT EDIT!


#ifndef TUTORIAL_MESSAGE_MULTWOINTS_H
#define TUTORIAL_MESSAGE_MULTWOINTS_H

#include <ros/service_traits.h>


#include <tutorial/MulTwoIntsRequest.h>
#include <tutorial/MulTwoIntsResponse.h>


namespace tutorial
{

struct MulTwoInts
{

typedef MulTwoIntsRequest Request;
typedef MulTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MulTwoInts
} // namespace tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial::MulTwoInts > {
  static const char* value()
  {
    return "22e1fb5e47d069b2b327ca34488a755a";
  }

  static const char* value(const ::tutorial::MulTwoInts&) { return value(); }
};

template<>
struct DataType< ::tutorial::MulTwoInts > {
  static const char* value()
  {
    return "tutorial/MulTwoInts";
  }

  static const char* value(const ::tutorial::MulTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial::MulTwoIntsRequest> should match
// service_traits::MD5Sum< ::tutorial::MulTwoInts >
template<>
struct MD5Sum< ::tutorial::MulTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::MulTwoInts >::value();
  }
  static const char* value(const ::tutorial::MulTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::MulTwoIntsRequest> should match
// service_traits::DataType< ::tutorial::MulTwoInts >
template<>
struct DataType< ::tutorial::MulTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial::MulTwoInts >::value();
  }
  static const char* value(const ::tutorial::MulTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial::MulTwoIntsResponse> should match
// service_traits::MD5Sum< ::tutorial::MulTwoInts >
template<>
struct MD5Sum< ::tutorial::MulTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::MulTwoInts >::value();
  }
  static const char* value(const ::tutorial::MulTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::MulTwoIntsResponse> should match
// service_traits::DataType< ::tutorial::MulTwoInts >
template<>
struct DataType< ::tutorial::MulTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial::MulTwoInts >::value();
  }
  static const char* value(const ::tutorial::MulTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL_MESSAGE_MULTWOINTS_H
