// Generated by gencpp from file tutorial/my_srv.msg
// DO NOT EDIT!


#ifndef TUTORIAL_MESSAGE_MY_SRV_H
#define TUTORIAL_MESSAGE_MY_SRV_H

#include <ros/service_traits.h>


#include <tutorial/my_srvRequest.h>
#include <tutorial/my_srvResponse.h>


namespace tutorial
{

struct my_srv
{

typedef my_srvRequest Request;
typedef my_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct my_srv
} // namespace tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial::my_srv > {
  static const char* value()
  {
    return "cd6995d1f27dd1f271e3dace09a45f6f";
  }

  static const char* value(const ::tutorial::my_srv&) { return value(); }
};

template<>
struct DataType< ::tutorial::my_srv > {
  static const char* value()
  {
    return "tutorial/my_srv";
  }

  static const char* value(const ::tutorial::my_srv&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial::my_srvRequest> should match
// service_traits::MD5Sum< ::tutorial::my_srv >
template<>
struct MD5Sum< ::tutorial::my_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::my_srv >::value();
  }
  static const char* value(const ::tutorial::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::my_srvRequest> should match
// service_traits::DataType< ::tutorial::my_srv >
template<>
struct DataType< ::tutorial::my_srvRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial::my_srv >::value();
  }
  static const char* value(const ::tutorial::my_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial::my_srvResponse> should match
// service_traits::MD5Sum< ::tutorial::my_srv >
template<>
struct MD5Sum< ::tutorial::my_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::my_srv >::value();
  }
  static const char* value(const ::tutorial::my_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::my_srvResponse> should match
// service_traits::DataType< ::tutorial::my_srv >
template<>
struct DataType< ::tutorial::my_srvResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial::my_srv >::value();
  }
  static const char* value(const ::tutorial::my_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL_MESSAGE_MY_SRV_H
